### ISSUE TITLE
Unauthorized domain for build preview channel deploy

### ISSUE THREAD

**Issue by aditmodhvadia** [FirebaseExtended/action-hosting-deploy#51]
I am using  Google sign-in provider which does not work when the hosting deploy bot deploys it when a PR is created on a preview channel, as the domain name is different than the one mentioned in the firebase config.

Please let me know if any further information is required.

**Comment by jhuleatt** [comment]
Hi @aditmodhvadia, this bug is discussed in detail in https://github.com/FirebaseExtended/action-hosting-deploy/issues/39. To summarize, it's a CLI bug that's being worked on [here](https://github.com/firebase/firebase-tools/pull/2736), but you can work around it for now by following these instructions:  https://github.com/FirebaseExtended/action-hosting-deploy/issues/39#issuecomment-714030778
