### ISSUE TITLE
Authentication Whitelist

### ISSUE THREAD

**Issue by HenryLeC** [FirebaseExtended/action-hosting-deploy#56]
# Preview Channels are not automatically added to authentication whitelist.

For preview channels to work they need to be added to the authentication whitelist, but for whatever reason they are not added on PRs

**Comment by jhuleatt** [comment]
Hi @HenryLeC, this bug is discussed in detail in https://github.com/FirebaseExtended/action-hosting-deploy/issues/39. To summarize, it's a CLI bug that is fixed in the latest version of firebase-tools ([fixed in this PR](https://github.com/firebase/firebase-tools/pull/2736)), and you can work around it by following these instructions:  https://github.com/FirebaseExtended/action-hosting-deploy/issues/39#issuecomment-714030778

Can you please verify that it works correctly with the latest version of firebase-tools?
