### ISSUE TITLE
Respect the `expires` option

### ISSUE THREAD

**Issue by mathiasbynens** [FirebaseExtended/action-hosting-deploy#7]
[The `expires` option](https://github.com/FirebaseExtended/action-hosting-deploy#expires-string) gets read here: https://github.com/FirebaseExtended/action-hosting-deploy/blob/de524e418e63c5c82a1b71a1b7e6c13461496a0f/src/deploy.ts#L91 but then its value doesn’t get used.

**Comment by jhuleatt** [comment]
This is intentional for now. I believe the CLI has a bug where it can't recognize arguments passed to the `--expires` option. For example, if I use `firebase-tools` version `8.10.0` and run:

`firebase hosting:channel:deploy my-channel --expires 7d --project=action-hosting-deploy-demo`

I get the error:

`Error: Failed to parse provided expire time "7d"`

**Comment by jhuleatt** [comment]
Added a warning to the readme: https://github.com/FirebaseExtended/action-hosting-deploy#expires-string

**Comment by rosslavery** [comment]
If I set the channel to `live` (aka a production deploy), will it still auto-expire after 7 days? I obviously don't want that :) 

Also the README example has an expires option set for the production example which may create problems for people copy-pasting without checking.

**Comment by jhuleatt** [comment]
Deploying to `live` causes the action to just run `firebase deploy --only hosting`, so no worries about expiration there: https://github.com/FirebaseExtended/action-hosting-deploy/blob/a17a591e8c1b4f9f4e728c0e11ee3c31ee61477b/src/deploy.ts#L114-L117

Since the action isn't setting an expiration, Hosting will default each channel to a 7 day expiration period, although that resets every time a new commit is added to a PR (causing the channel to be redeployed)

**Comment by jhuleatt** [comment]
btw, the bug that caused the CLI not to be able to parse `--expires` was fixed in this PR: https://github.com/firebase/firebase-tools/pull/2608

So once that is released, we can update this action to listen to the `expires` option.
